### ISSUE TITLE
responsive page accueil

### ISSUE THREAD

**Issue by AtnRic** [AtnRic/red-november#1]
passer la page d'accueil en display grid pour le responsive.

- les boutons pourrons être affichés correctement en bas de l'écran sur toutes les tailles d'écran.
- la section "Veuillez activer le son." et le texte ne se chevaucheront plus (une ligne différente sur la grid pour chaque élément)

**Comment by NguyenLyy** [comment]
I want to do it. Can you guide me!

**Comment by AtnRic** [comment]
Hello! Thank you for your suggestion!
Unfortunately, this project is a school project that has to be done by me and @AdrVrh only :(
But you can help us by reporting possible bugs!
